version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: traceco2_db
    restart: always
    environment:
      POSTGRES_USER: traceco2
      POSTGRES_PASSWORD: traceco2
      POSTGRES_DB: traceco2
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: traceco2_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://traceco2:traceco2@postgres:5432/traceco2
    ports:
      - '3333:3333'

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: traceco2_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db-data:
